FORMAT: 1A
HOST: https://www.caa.com/api/v1

# Aircraft Registration API

This API exposes registration data and additional functionalities to enable developers and interested parties build applications and tools that utilize the data in the registry. The API is JSON-rest based and uses standard HTTP response codes to indicate API errors and successes.

#### Token Authentication
The registration data is exposed via a OAUTH token that is linked to a user account on the system. To generate a OAUTH token and credentials you must first create a account and follow instructions at the [Token Generation page](https://www.caa.com/accounts/token/) on our website. If your account is for specific law enforcement bodies or regulatory bodies, you will be required to request privilaged access, you can get your tokens by filling out the form here [Privilaged Access request](https://www.caa.com/accounts/token/) 


#### Access
This API supports only **https://** connections via the API. ``http://`` connections will be given a automatic HTTP 301 response.


#### Pagination
API responses are paginated. The default page size is 20; you can alter this by adding the ``page_size`` parameter to your request.


#### Limits
The API system throttles reqests to 1000 per hour for a particular token after which it will deny repeated requests for 30 minutes. If you require unthrottled access, please contact us using the [Special Access request](https://www.caa.com/accounts/privilaged/) 


#### Response Codes
The API uses standard HTTP response codes to communicate the status of the request. In general, 2xx codes signify success and 4xx codes signify failure, and these codes are generally associated with an invalid parameter being provided in the request. A 5xx code is a general server failure on our side. Please contact our support team if you encounter 5xx errors. Please refer to the Wikipedia page on [HTTP request codes](https://www.wikipedia.org/HTTP_Respose_Codes/) for more information 


## Group Person and Address API
Resources related to adding person and addresses in the API


## Add a new Person [/person/add/]

### Add new person [POST]
Adds a new person (Contact or Pilot) to the database

+ Request (application/json)
    + Headers

            Authorization: Token ABC123
            
    + Body

            {
              "first_name": "Jeanie",
              "middle_name": "",
              "last_name": "Modesta",
              "email": "dludgrove7@posterous.com", 
              "phone_number": "+499122992107", 
              "identification_number": "IE7847623905F", 
              "social_security_number": "THG033GE", 
              "date_of_birth": "27-02-1989"
            }

    + Schema

            {
              "$schema": "http://json-schema.org/draft-07/schema#",
              "type": "object",
              "properties": {
                "first_name": {
                  "type": "string"
                },
                "middle_name": {
                  "type": "string"
                },
                "last_name": {
                  "type": "number"
                },
                "email": {
                  "type": "number"
                },
                "phone_number": {
                  "type": "string"
                },
                "identification_number": {
                  "type": "string"
                },
                "social_security_number": {
                  "type": "string"
                },
                "date_of_birth": {
                  "type": "string"
                }
                  "minItems": 1
                }
              }
            }
            
+ Response 200 (application/json)

            {
              "id": "e9e5a30b-00f5-4bd4-b07b-c8fa3a85fb17",
              "first_name": "Jeanie",
              "middle_name": "",
              "last_name": "Modesta",
              "email": "dludgrove7@posterous.com", 
              "phone_number": "+499122992107", 
              "identification_number": "IE7847623905F", 
              "social_security_number": "THG033GE", 
              "date_of_birth": "27-02-1989",
              "created_at": "2018-03-03T18:58:10Z",
              "updated_at": "2018-03-03T18:58:10Z"
            }
              


## Add a new Address [/address/add/]

### Add new address [POST]
Adds a entry in the address database

+ Request (application/json)
    + Headers

            Authorization: Token ABC123
            
    + Body

            {
              "address_line_1": "107  West Lane, DALMICHY",
              "address_line_2": "",
              "address_line_3": "", 
              "postcode": "D02 DH42", 
              "city": "SHARRINGTON", 
              "country": "GB", 
            }

    + Schema

            {
              "$schema": "http://json-schema.org/draft-07/schema#",
              "type": "object",
              "properties": {
                "address_line_1": {
                  "type": "string"
                },
                "address_line_2": {
                  "type": "string"
                },
                "address_line_3": {
                  "type": "string"
                },
                "postcode": {
                  "type": "string"
                },
                "city": {
                  "type": "string"
                },
                "country": {
                  "type": "string"
                },
                  "minItems": 1
                }
              }
            }
            
+ Response 200 (application/json)

            {
              "id":"cbe99049-4b39-4410-b46a-d07f045e1bdc",
              "address_line_1": "107  West Lane, DALMICHY",
              "address_line_2": "",
              "address_line_3": "", 
              "postcode": "D02 DH42", 
              "city": "SHARRINGTON", 
              "country": "GB", 
              "created_at": "2018-03-03T18:58:10Z",
              "updated_at": "2018-03-03T18:58:10Z"
            }
              


## Group Operator API
Resources related to Operator Registration in the API

## Add a new Operator [/operators/add/]

### Add new operator [POST]
Adds a entry in the operator database

+ Request (application/json)
    + Headers

            Authorization: Token ABC123
            
    + Body

            {
              "company_name": "Aalto-korkeakoulusäätiö",
              "website": "aalto.fi",
              "email": "mikko.raskinen@aalto.fi", 
              "telephone": "0505270032", 
              "address": "6249a5b0-d052-499e-8bcc-0c1f49e7b3b6", 
              "type":"open",
              "operational_authorizations": ["SORA"],
              "authorized_applications": ["Photographing, videotaping","Press, media","Inspection of buildings or roofs","Inspection of other constructions, e.g. bridges","Measurement of mobile phone networks or other telecommunication networks","RPAS flight training"],
              "vat_number":"DE5396483F",
              "company_number":"45321",
              "country":"GB"
              "insurance_number":"349453EF"
            }

    + Schema

            {
              "$schema": "http://json-schema.org/draft-07/schema#",
              "type": "object",
              "properties": {
                "company_name": {
                  "type": "string"
                },
                "website": {
                  "type": "string"
                },
                "telephone": {
                  "type": "number"
                },
                "postcode": {
                  "type": "number"
                },
                "address": {
                  "type": "string"
                },
                "email": {
                  "type": "string"
                },
                "type": {
                  "type": "string"
                },
                "vat_number": {
                  "type": "string"
                },
                "insurance_number": {
                  "type": "string"
                },
                "company_number": {
                  "type": "string"
                },
                "country": {
                  "type": "string"
                },
                "operational_authorizations": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  },
                  "minItems": 1
                },
                "authorized_applications": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  },
                  "minItems": 1
                }
              }
            }
            
+ Response 200 (application/json)

            {
              "id": "4f140e59-98c3-4bc2-bf30-eec982c132ad",
              "company_name": "Aalto-korkeakoulusäätiö",
              "website": "aalto.fi",
              "email": "mikko.raskinen@aalto.fi", 
              "telephone": "0505270032", 
              "address": "Otakaari 24", 
              "postcode": "02150", 
              "city": "espoo",
              "operator_type":"open",
              "contact_name":"John Smith",
              "contact_id":"9921-181-987", 
              "operational_authorizations": ["SORA"],
              "authorized_applications": ["Photographing, videotaping","Press, media","Inspection of buildings or roofs","Inspection of other constructions, e.g. bridges","Measurement of mobile phone networks or other telecommunication networks","RPAS flight training"],
              "vat_number":"DE5396483F",
              "company_number":"45321",
              "insurance_number":"349453EF",
              "created_at": "2018-03-03T18:58:10Z",
              "updated_at": "2018-03-03T18:58:10Z"
            }
              


## All Operators [/operators/]

### List all operators [GET]
Returns a list of operators in the registry
    
+ Request (application/json)
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)
        
        [
          {
            "id": "4f140e59-98c3-4bc2-bf30-eec982c132ad",
            "companyname": "1000 feet Oy",
            "postcode": "01370",
            "exipration": "2021-05-31",
            "created_at": "2018-03-03T18:58:10Z",
            "updated_at": "2018-03-03T18:58:10Z"
          },
          {
            "id": "4f140e59-98c3-4bc2-bf30-eec982c132ad",
            "companyname": "Aalto-korkeakoulusäätiö",
            "postcode": "02150",
            "created_at": "2018-03-03T18:58:10Z",
            "updated_at": "2018-03-03T18:58:10Z"
          }
        ]


## Single Operator Details [/operators/{operatorid}/]

### Get a single operator [GET]
Returns all the details of a single operator available in the database. The operator id is the unique ID assoicated with the operator that is in the form of a uuid.

+ Parameters
    + operatorid: 4f140e59-98c3-4bc2-bf30-eec982c132ad (string) - The ID of a operator in the form of an string
    
+ Request (application/json)
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)

    + Attributes (object)
        + id: 250FF (string, required)
        + company_name: Aalto Korkeakoulusäätiö (string) - Registered name of the operator
        + email: mikko.raskinen@aalto.fi (string) - email contact address of operator

            A valid email address per [IETF](https://tools.ietf.org/html/rfc5322)
            
        + website: aalto.fi (string) - Web address of operator

    + Body

            {
                "id": "41174c3f-e86c-4e5a-a629-32d4d9da6011",
                "company_name": "A.J. August Photography",
                "website": "august.com",
                "email": "aj@august.com",
                "phone_number": "+497221816880"
            }

## Privilaged Single Operator Details [/operators/{operatorid}/privilaged/]

### Get a operator (Privilaged) [GET]
This is a privilaged request made by a interested party that has special access privilages in the registry. Returns all the details of a single operator available in the database. The operatorid is the unique ID assoicated with the operator that is in the form of a uuid. 

+ Parameters
    + operatorid: 4f140e59-98c3-4bc2-bf30-eec982c132ad (string) - The ID of a operator in the form of an string
    
+ Request (application/json)
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)

    + Attributes (object)
        + id: 250FF (string, required)
        + company_name: Aalto Korkeakoulusäätiö (string) - Registered name of the operator
        + email: mikko.raskinen@aalto.fi (string) - email contact address of operator

            A valid email address per [IETF](https://tools.ietf.org/html/rfc5322)
            
        + website: aalto.fi (string) - Web address of operator
        + address: Otakaari 24 (string) - Postal Address of the operator
        + postcode: 02150 (number) - Postcode of the registered office of the opeartor

    + Body

            {
                "id": "41174c3f-e86c-4e5a-a629-32d4d9da6011",
                "company_name": "A.J. August Photography",
                "website": "august.com",
                "email": "aj@august.com",
                "operator_type": 0,
                "address": {
                    "id": "8ddda026-2995-44ef-9eab-55e396eaef0d",
                    "address_line_1": "Claureen Lahinch rd Ennis",
                    "address_line_2": "",
                    "address_line_3": "",
                    "postcode": "D02VE22",
                    "city": "Westport",
                    "country": "IE",
                    "created_at": "2019-04-25T10:02:33.691494Z",
                    "updated_at": "2019-04-25T10:02:33.715107Z"
                },
                "operational_authorizations": [
                    "SORA"
                ],
                "authorized_activities": [
                    "videotaping",
                    "photographing"
                ],
                "created_at": "2018-09-04T12:20:30Z",
                "updated_at": "2018-09-04T12:20:30Z"
            }

## Update Existing Operator Details [/operators/update/{operatorid}/]

### Update operator details [POST]
Updates a entry in the operator database with modified details. 

+ Parameters
    + operatorid: 4f140e59-98c3-4bc2-bf30-eec982c132ad (string) - The ID of a operator in the form of an string
    
+ Request (application/json)
    + Headers

            Authorization: Token ABC123
            
    + Body

            {
              "insurance_number": "20T3VG"
            }

    + Schema

            {
              "$schema": "http://json-schema.org/draft-07/schema#",
              "type": "object",
              "properties": {
                "company_name": {
                  "type": "string"
                },
                "website": {
                  "type": "string"
                },
                "telephone": {
                  "type": "number"
                },
                "postcode": {
                  "type": "number"
                },
                "email": {
                  "type": "string"
                },
                "type": {
                  "type": "string"
                },
                "vat_number": {
                  "type": "string"
                },
                "insurance_number": {
                  "type": "string"
                },
                "company_number": {
                  "type": "string"
                },
                "operational_authorizations": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  },
                  "minItems": 1
                },
                "authorized_applications": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  },
                  "minItems": 1
                }
              }
            }
            
+ Response 200 (application/json)

            {
                "id": "41174c3f-e86c-4e5a-a629-32d4d9da6011",
                "company_name": "A.J. August Photography",
                "website": "august.com",
                "email": "aj@august.com",
                "phone_number": "+497221816880"
            }
              

## Group Contact API
Resources related to Contacts with in the Registration in the API


## All Contacts [/contacts/]

### List all contacts [GET]
Returns a list of contact people in the registry
    
+ Request (application/json)
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)
        
        [
            {
                "id": "a7646ce2-f7df-48a9-9ff8-98dfd04794be",
                "operator": {
                    "id": "41174c3f-e86c-4e5a-a629-32d4d9da6011",
                    "company_name": "A.J. August Photography",
                    "website": "august.com",
                    "email": "aj@august.com",
                    "phone_number": "+497221816880"
                },
                "person": {
                    "id": "e61a74c8-7aa4-4dd3-82ba-11b174a44870",
                    "first_name": "Catherine",
                    "middle_name": null,
                    "last_name": "OConor",
                    "email": "catherine@gmail.com",
                    "created_at": "2019-04-25T10:02:33.734983Z",
                    "updated_at": "2019-04-25T10:02:33.740987Z"
                },
                "updated_at": "2018-09-04T12:20:30Z"
            },
            {
                "id": "c3ae2bb0-19f6-4738-a53b-cdb0acbaf5b1",
                "operator": {
                    "id": "566d63bb-cb1c-42dc-9a51-baef0d0a8d04",
                    "company_name": "Electric Inspection",
                    "website": "electricinspection.com",
                    "email": "contact@electricinspection.com",
                    "phone_number": "+4930292487"
                },
                "person": {
                    "id": "a2f3b8b2-183d-44df-9254-83aca26d01c0",
                    "first_name": "Molly",
                    "middle_name": "S",
                    "last_name": "Storey",
                    "email": "molly@hotmail.com",
                    "created_at": "2019-04-25T10:02:33.734983Z",
                    "updated_at": "2019-04-25T10:02:33.740987Z"
                },
                "updated_at": "2018-09-04T12:20:30Z"
            }
        ]

## Single Contact Details [/contacts/{contactid}/]

### Get a single contact [GET]
Returns all the details of a single contact and basic information about the contact person available in the database. The contact id is the unique ID assoicated with a contact person for the operator that is in the form of a uuid.

+ Parameters
    + contactid: 4f140e59-98c3-4bc2-bf30-eec982c132ad (string, required) - The ID of a contact person for a operator in the form of an string
    
+ Request (application/json)
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)

    + Attributes (object)
        + id: 250FF (string, required)
        + company_name: Aalto Korkeakoulusäätiö (string) - Registered name of the operator
        + contact_name: Aalto Korkeakoulusäätiö (string) - Name of the contact person in the operator
        + email: mikko.raskinen@aalto.fi (string) - email contact address of operator

            A valid email address per [IETF](https://tools.ietf.org/html/rfc5322)
            
        

    + Body

            {
                "id": "a7646ce2-f7df-48a9-9ff8-98dfd04794be",
                "operator": {
                    "id": "41174c3f-e86c-4e5a-a629-32d4d9da6011",
                    "company_name": "A.J. August Photography",
                    "website": "august.com",
                    "email": "aj@august.com",
                    "phone_number": "+497221816880"
                },
                "person": {
                    "id": "e61a74c8-7aa4-4dd3-82ba-11b174a44870",
                    "first_name": "Catherine",
                    "middle_name": null,
                    "last_name": "OConor",
                    "email": "catherine@gmail.com",
                    "created_at": "2019-04-25T10:02:33.734983Z",
                    "updated_at": "2019-04-25T10:02:33.740987Z"
                },
                "updated_at": "2018-09-04T12:20:30Z"
            }

## Update Existing Contact Details [/contacts/update/{contactid}/]

### Update contact details [POST]
Updates a contact point entry in the operator database with modified details. 

+ Parameters
    + contactid: 4f140e59-98c3-4bc2-bf30-eec982c132ad (string, required) - The ID of a operator in the form of an string
    
+ Request (application/json)
    + Headers

            Authorization: Token ABC123
            
    + Body

            {
              "role_type": "1"
            }

    + Schema

            {
              "$schema": "http://json-schema.org/draft-07/schema#",
              "type": "object",
              "properties": {
                "role_type": {
                  "type": "number"
                }
              }
            }
            
+ Response 200 (application/json)

            {
                "id": "a7646ce2-f7df-48a9-9ff8-98dfd04794be",
                "operator": {
                    "id": "41174c3f-e86c-4e5a-a629-32d4d9da6011",
                    "company_name": "A.J. August Photography",
                    "website": "august.com",
                    "email": "aj@august.com",
                    "phone_number": "+497221816880"
                },
                "person": {
                    "id": "e61a74c8-7aa4-4dd3-82ba-11b174a44870",
                    "first_name": "Catherine",
                    "middle_name": null,
                    "last_name": "OConor",
                    "email": "catherine@gmail.com",
                    "created_at": "2019-04-25T10:02:33.734983Z",
                    "updated_at": "2019-04-25T10:02:33.740987Z"
                },
                "role_type": 0,
                "updated_at": "2018-09-04T12:20:30Z"
            }

## Group Pilot API
Resources related to Contacts with in the Registration in the API


## All Pilots [/pilots/]

### List all pilots [GET]
Returns a list of pilots in the registry
    
+ Request (application/json)
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)

        [
            {
                "id": "d4b8aa2c-0a52-4adc-806a-f363deb6a1e0",
                "operator": {
                    "id": "566d63bb-cb1c-42dc-9a51-baef0d0a8d04",
                    "company_name": "Electric Inspection",
                    "website": "electricinspection.com",
                    "email": "contact@electricinspection.com",
                    "phone_number": "+4930292487"
                },
                "is_active": true,
                "person": {
                    "id": "32153c3b-663b-41e4-afc2-47127a713704",
                    "first_name": "Mickey",
                    "middle_name": "Richard",
                    "last_name": "Matheny",
                    "email": "MickeyRMatheny@teleworm.us",
                    "created_at": "2019-04-25T10:02:33.734983Z",
                    "updated_at": "2019-04-25T10:02:33.740987Z"
                },
                "updated_at": "2018-09-04T12:20:30Z"
            },
            {
                "id": "2f15a395-65a3-4a73-a492-57c7c470d527",
                "operator": {
                    "id": "41174c3f-e86c-4e5a-a629-32d4d9da6011",
                    "company_name": "A.J. August Photography",
                    "website": "august.com",
                    "email": "aj@august.com",
                    "phone_number": "+497221816880"
                },
                "is_active": true,
                "person": {
                    "id": "5434e29a-d7e6-4462-ab30-73c7a074915c",
                    "first_name": "Modesta",
                    "middle_name": "Jeanie",
                    "last_name": "Strauss",
                    "email": "dludgrove7@posterous.com",
                    "created_at": "2019-04-25T10:02:33.734983Z",
                    "updated_at": "2019-04-25T10:02:33.740987Z"
                },
                "updated_at": "2018-09-04T12:20:30Z"
            }
        ]

## Single Pilot Details [/pilots/{pilotid}/]

### Get a single pilot [GET]
Returns all the details of a single pilot and basic information about the pilot available in the database. The pilot id is the unique ID assoicated with a pilot for the operator that is in the form of a uuid.

+ Parameters
    + pilotid: 4f140e59-98c3-4bc2-bf30-eec982c132ad (string, required) - The ID of a pilot for a operator in the form of an string
    
+ Request (application/json)
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)

    + Attributes (object)
        + id: 250FF (string, required)
        + operator: 250FF (string)- Registered name of the operator
        + first_name: Modesta (string) - First Name of the pilot
        + last_name: Strauss (string) - Last Name of the pilot
        + phone_number: +499122992107 (string) - Phone number of the pilot
        + email: dludgrove7@posterous.com (string) - email of the pilot

            A valid email address per [IETF](https://tools.ietf.org/html/rfc5322)
       
    + Body

            {
                "id": "d4b8aa2c-0a52-4adc-806a-f363deb6a1e0",
                "operator": {
                    "id": "566d63bb-cb1c-42dc-9a51-baef0d0a8d04",
                    "company_name": "Electric Inspection",
                    "website": "electricinspection.com",
                    "email": "contact@electricinspection.com",
                    "phone_number": "+4930292487"
                },
                "is_active": true,
                "person": {
                    "id": "32153c3b-663b-41e4-afc2-47127a713704",
                    "first_name": "Mickey",
                    "middle_name": "Richard",
                    "last_name": "Matheny",
                    "email": "MickeyRMatheny@teleworm.us",
                    "created_at": "2019-04-25T10:02:33.734983Z",
                    "updated_at": "2019-04-25T10:02:33.740987Z"
                },
                "updated_at": "2018-09-04T12:20:30Z"
            }
            
## Update Existing Pilot Details [/contacts/update/{pilotid}/]

### Update pilot details [POST]
Updates a pilot entry in the operator database with modified details. 

+ Parameters
    + pilotid: 4f140e59-98c3-4bc2-bf30-eec982c132ad (string, required) - The ID of a pilot in the form of an string
    
+ Request (application/json)
    + Headers

            Authorization: Token ABC123
            
    + Body

            {
              "is_active": 1
            }

    + Schema

            {
              "$schema": "http://json-schema.org/draft-07/schema#",
              "type": "object",
              "properties": {
                "is_active": {
                  "type": "number"
                }
              }
            }
            
+ Response 200 (application/json)

            {
                "id": "2f15a395-65a3-4a73-a492-57c7c470d527",
                "operator": "41174c3f-e86c-4e5a-a629-32d4d9da6011",
                "is_active": true,
                "first_name": "Jane",
                "last_name": "Strauss",
                "email": "dludgrove7@posterous.com",
                "phone_number": "+499122992107",
                "updated_at": "2018-09-04T12:20:30Z"
            }
 

## Group Aircraft API

## Equipment registered by a Operator [/operators/{operatorid}/aircraft/]

### List equipment registered [GET]
Returns a list of all the equipment active and inactive that are registered by the operator


+ Parameters
    + operatorid: 4f140e59-98c3-4bc2-bf30-eec982c132ad (string) - The ID of a operator in the form of an string

+ Request
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)

        [
            {
                "id": "0797d9ef-02d9-41cf-93ff-439aaf1609ae",
                "mass": 300,
                "manufacturer": "6f9cd973-15b9-4066-b4d0-1e8bbd0f279d",
                "model": "Parrot",
                "esn": "4D4652310000000000000000313233343436373839414243",
                "maci_number": "86ac-42dc-8d19",
                "status": 1,
                "registration_mark": null,
                "sub_category": 7,
                "type_certificate": {
                    "id": "75f358c6-e8d3-46aa-a3de-172bdcea469d",
                    "type_certificate_id": "1dc42b2a-7e3f-4e87-b23d-353ec8a06705",
                    "type_certificate_issuing_country": "IRE",
                    "type_certificate_holder": "Agro Products Inc.",
                    "type_certificate_holder_country": "IRE"
                },
                "created_at": "2018-09-04T12:20:30Z",
                "master_series": null,
                "series": null,
                "popular_name": "Parrot 2",
                "icao_aircraft_type_designator": "HS20",
                "max_certified_takeoff_weight": "0.000",
                "updated_at": "2018-09-04T12:20:30Z"
            }
        ]

### Add a new Aircraft equipment [POST]
Add a new Aircraft assigned to the operator

+ Parameters
    + operatorid: 4f140e59-98c3-4bc2-bf30-eec982c132ad (string) - The ID of a operator in the form of an string
    
+ Request (application/json)
    + Headers

            Authorization: Token ABC123
            
    + Body

            {
              "manufacturer": "DJI",
              "model": "Parrot",
              "mass": "300",
              "esn": "5G6532640000000000000000823050083171098833641055",
              "maci_number": "3d9-23",
              "status": "active"
            }

    + Schema

            {
              "$schema": "http://json-schema.org/draft-07/schema#",
              "type": "object",
              "properties": {
                "manufacturer": {
                  "type": "string"
                },
                "model": {
                  "type": "string"
                },
                "mass": {
                  "type": "number"
                },
                "esn": {
                  "type": "string"
                },
                "maci_number": {
                  "type": "string"
                }
              }
            }
            
+ Response 200 (application/json)

            {
              "equipment_id": "26bc3e7710ea"
            }
    
## Update registered equipment [/operators/{operatorid}/aircraft/update/{aircraftid}]

### Update a existing Aircraft Detail [POST]
Updates a entry in the operator database with modified details. 

+ Parameters
    + operatorid: 4f140e59-98c3-4bc2-bf30-eec982c132ad (string) - The ID of a operator in the form of an string
    + aircraftid: 26bc3e7710ea (string) - The ID of a operator in the form of an string
    
+ Request (application/json)
    + Headers

            Authorization: Token ABC123
            
    + Body

            {
              "status": "inactive"
            }

    + Schema

            {
              "$schema": "http://json-schema.org/draft-07/schema#",
              "type": "object",
              "properties": {
                "manufacturer": {
                  "type": "string"
                },
                "model": {
                  "type": "string"
                },
                "mass": {
                  "type": "number"
                },
                "esn": {
                  "type": "string"
                },
                "maci_number": {
                  "type": "string"
                }
              }
            }
            
+ Response 200 (application/json)

            {
                "equipment_id": "26bc3e7710ea",
                "manufacturer": "DJI",
                "model": "Parrot",
                "mass": "300",
                "esn": "5G6532640000000000000000823050083171098833641055",
                "maci_number": "3d9-23",
                "status": "active",
                "created_at": "2011-04-10T20:09:31Z",
                "updated_at": "2014-03-03T18:58:10Z"
            }



## Single Aircraft Details [/aircraft/{aircraftid}]

### Get a single Aircraft [GET]
Get information about a Aircraft by looking up its ESN

+ Parameters
    + aircraftid: 4D4652310000000000000000313233343436373839414243 (string) - ESN of Aircraft, ESN = [Manufacturer’s Code] [Serial Number] [IMEISV] [Performative Characteristics]

    
+ Request (application/json)
    + Headers

            Authorization: Token ABC123
            
    + Body

            {
              "status": "inactive"
            }

    + Schema

            {
              "$schema": "http://json-schema.org/draft-07/schema#",
              "type": "object",
              "properties": {
                "manufacturer": {
                  "type": "string"
                },
                "model": {
                  "type": "string"
                },
                "mass": {
                  "type": "number"
                },
                "esn": {
                  "type": "string"
                },
                "maci_number": {
                  "type": "string"
                }
              }
            }
            
+ Response 200 (application/json)

            {
                "equipment_id": "26bc3e7710ea",
                "manufacturer": "DJI",
                "model": "Parrot",
                "mass": "300",
                "esn": "5G6532640000000000000000823050083171098833641055",
                "maci_number": "3d9-23",
                "status": "active",
                "created_at": "2011-04-10T20:09:31Z",
                "updated_at": "2014-03-03T18:58:10Z"
            }

